[package]
name = "validate-facet"
version = "0.1.0"
edition = "2021"

[dependencies]
# CLI and async runtime
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
eyre = "0.6"

# Progress and logging
indicatif = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Parallelism
rayon = "1.8"
futures = "0.3"

# Random sampling
rand = "0.8"

# HTTP client for RPC
reqwest = { version = "0.11", features = ["json"] }

# Kona dependencies
kona-derive = { path = "../../crates/protocol/derive" }
kona-protocol = { path = "../../crates/protocol/protocol" }
kona-genesis = { path = "../../crates/protocol/genesis" }
kona-providers-alloy = { path = "../../crates/providers/providers-alloy" }

# Alloy dependencies
alloy-primitives = "0.8"
alloy-provider = "0.15"
alloy-eips = "0.15"
alloy-rpc-types-eth = "0.15"
op-alloy-network = "0.15"

# File system
tempfile = "3.8"