[package]
name = "kona-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Workspace
kona-client = { path = "../client", version = "0.1.0" }
kona-common = { path = "../../crates/common", version = "0.0.2" }
kona-preimage = { path = "../../crates/preimage", version = "0.0.2" }
kona-mpt = { path = "../../crates/mpt", version = "0.0.2" }
kona-primitives = { path = "../../crates/primitives", version = "0.0.1", features = ["online"] }
kona-derive = { path = "../../crates/derive", version = "0.0.2", features = ["online"] }

# Alloy & Revm
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-provider.workspace = true
alloy-transport-http.workspace = true 
alloy-rpc-client.workspace = true 
alloy-rpc-types.workspace = true
revm = { workspace = true, features = ["std", "c-kzg", "secp256k1", "portable", "blst"] }

# General
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
reqwest.workspace = true
tokio.workspace = true
futures.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
command-fds.workspace = true
os_pipe.workspace = true
