[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["clabby"]
repository = "https://github.com/anton-rs/kona"
homepage = "https://github.com/anton-rs/kona"
exclude = ["**/target", "benches/", "tests"]

[workspace.dependencies]
anyhow = "1.0.75"
tracing = "0.1.40"

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.bench]
debug = true
