[package]
name = "kona-derive"
description = "A no_std derivation pipeline implementation for the OP Stack"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Workspace Alloy Dependencies
alloy-eips.workspace = true
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-primitives = { workspace = true, features = ["rlp", "k256"] }
op-alloy-consensus = { workspace = true, features = ["k256"] }

# Other Workspace Dependencies
lru.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true

# Local
kona-primitives = { path = "../primitives", version = "0.0.1", default-features = false }

# External
hashbrown = "0.14.5"
unsigned-varint = "0.8.0"
miniz_oxide = "0.8.0"
brotli = { version = "6.0.0", default-features = false }
alloc-no-stdlib = "2.0.4"

# `serde` feature dependencies
serde = { version = "1.0.203", default-features = false, features = ["derive"], optional = true }

# `online` feature dependencies
alloy-transport = { version = "0.2", default-features = false, optional = true }
alloy-provider = { version = "0.2", default-features = false, optional = true }
reqwest = { version = "0.12.4", default-features = false, optional = true }

# `metrics` feature dependencies
lazy_static = { version = "1.5.0", optional = true }
prometheus = { version = "0.13.4", features = ["process"], optional = true }

# `test-utils` feature dependencies
spin = { workspace = true, optional = true }
tracing-subscriber = { version = "0.3.18", optional = true }
alloy-node-bindings = { version = "0.2", default-features = false, optional = true }
alloy-transport-http = { version = "0.2", optional = true } 
alloy-rpc-client = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.38", features = ["full"] }
proptest = "1.4.0"
tracing-subscriber = "0.3.18"
alloy-node-bindings = { version = "0.2", default-features = false }
serde_json = { version = "1.0.117", default-features = false }

[features]
default = ["serde"]
serde = [
  "dep:serde",
  "kona-primitives/serde",
  "alloy-primitives/serde",
  "alloy-consensus/serde",
  "op-alloy-consensus/serde"
]
metrics = ["dep:prometheus", "dep:lazy_static"]
online = [
  "dep:alloy-provider",
  "dep:alloy-transport",
  "dep:reqwest",
  "alloy-provider/reqwest",
  "alloy-consensus/serde",
  "kona-primitives/online",
]
test-utils = [
  "dep:spin",
  "dep:alloy-transport-http",
  "dep:alloy-node-bindings",
  "dep:tracing-subscriber",
  "dep:alloy-rpc-client",
  "alloy-transport-http/reqwest"
]
