[package]
name = "kt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
exclude = ["tests"]

[dependencies]
# Workspace
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rlp.workspace = true

# Local
kona-derive = { path = "../../crates/derive", version = "0.0.2", features = ["online"] }
kona-executor = { path = "../../crates/executor", version = "0.0.1" }
kona-mpt = { path = "../../crates/mpt", version = "0.0.2" }
kona-primitives = { path = "../../crates/primitives", version = "0.0.1", features = ["online"] }

# External
serde_json = { version = "1.0.117", default-features = false }
tracing-subscriber = "0.3.18"
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6" # For op-test-vector dependency
clap = { version = "4", features = ["derive", "env"] }
op-test-vectors = { git = "https://github.com/ethereum-optimism/tests", branch = "cl/t8n-reth" }
include_directory = "0.1.1"
alloy-trie = "0.4.1"
itertools = "0.13.0"
