[package]
name = "kona-primitives"
description = "Primitive types for kona crates"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
spin.workspace = true
tracing.workspace = true
alloy-consensus.workspace = true
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
hashbrown = "0.14.5"

# SCR Repo Primitives
superchain-primitives = { version = "0.3.1", default-features = false }

# `serde` feature dependencies
serde = { version = "1.0.203", default-features = false, features = ["derive"], optional = true }

# `online` feature dependencies
revm = { workspace = true, optional = true }
sha2 = { version = "0.10.8", default-features = false, optional = true }
c-kzg = { version = "1.0.2", default-features = false, optional = true }

[dev-dependencies]
serde_json = { version = "1.0.117", default-features = false }

[features]
default = ["serde"]
serde = ["dep:serde", "superchain-primitives/serde"]
online = ["dep:c-kzg", "dep:sha2", "dep:revm"]
