[package]
name = "kona-client"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Workspace
kona-common = { path = "../../crates/common", version = "0.0.2" }
kona-common-proc = { path = "../../crates/common-proc", version = "0.0.2" }
kona-preimage = { path = "../../crates/preimage", version = "0.0.2" }
kona-mpt = { path = "../../crates/mpt", version = "0.0.2" }
kona-derive = { path = "../../crates/derive", default-features = false, version = "0.0.2" }
kona-executor = { path = "../../crates/executor", version = "0.0.1" }
kona-primitives = { path = "../../crates/primitives", version = "0.0.1", features = ["serde"] }

# Revm + Alloy
revm.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true

# General
cfg-if.workspace = true
anyhow.workspace = true
lru.workspace = true
spin.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true

# `tracing-subscriber` feature dependencies
tracing-subscriber = { workspace = true, optional = true }

[features]
tracing-subscriber = ["dep:tracing-subscriber"]

[[bin]]
name = "kona"
path = "src/kona.rs"
