[package]
name = "kona-common"
description = "Common traits and utilities for Kona"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
# workspace
anyhow.workspace = true

# external
num = { version = "0.4.1", default-features = false }
good_memory_allocator = "0.1.7"
