[book]
authors = ["clabby"]
language = "en"
multilingual = false
src = "src"
title = "The Kona Book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.template]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
