name: Test Fixtures

on:
  pull_request:
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  derivation-fixtures:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run kdn
        run: just test-derivation
